version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: postgres_tienda
    restart: always
    environment:
      POSTGRES_USER: benja
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: tienda_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_tienda
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

  backend:
    build: ./server
    container_name: backend_tienda
    restart: always
    env_file:
      - ./server/.env
    environment:
      # Sobreescribimos el DB_HOST para que apunte al contenedor db en lugar de localhost
      - DB_HOST=db
    depends_on:
      - db

  frontend:
    build: ./client
    container_name: frontend_tienda
    restart: always
    depends_on:
      - backend

  caddy:
    image: caddy:2-alpine
    container_name: caddy_tienda
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - frontend
      - backend

volumes:
  postgres_data:
  caddy_data:
  caddy_config:
